### ISSUE TITLE
Add Unity Pro Color Support

### ISSUE THREAD

**Issue by MichaelKatic** [TinyPHX/Readme#31]

**Comment by Darkranium** [comment]
Here is how it currently looks like on Unity Pro

![IM_screenshot_2019-10-07-14-16-16](https://user-images.githubusercontent.com/9681014/66349173-1eacd280-e90d-11e9-8f50-c5e6b4d40359.png)

**Comment by MichaelKatic** [comment]
This is working and will be merged shortly!

![image](https://user-images.githubusercontent.com/3880024/67712605-8fca2d80-f981-11e9-92b9-a3cbc23b21e2.png)

![image](https://user-images.githubusercontent.com/3880024/67712659-a5d7ee00-f981-11e9-995d-06e9db53b02b.png)
